# Generated by Django 3.0.3 on 2020-05-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='背景图片')),
                ('bak_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注1')),
                ('bak_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注2')),
                ('bak_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注3')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='素材名称')),
                ('is_show_name', models.BooleanField(default=False, verbose_name='是否显示名称')),
                ('name_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称字体大小')),
                ('name_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称字体颜色')),
                ('name_loc', models.IntegerField(verbose_name='名称位置')),
                ('loc_left', models.CharField(max_length=20, verbose_name='位置-左')),
                ('loc_top', models.CharField(max_length=20, verbose_name='位置-上')),
                ('size_width', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标宽度')),
                ('size_height', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标高度')),
                ('icon_image', models.ImageField(upload_to='', verbose_name='图标图片')),
                ('content_image', models.URLField(blank=True, null=True, verbose_name='点击后显示内容URL')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoundMap.SoundMap')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='素材名称')),
                ('is_show_name', models.BooleanField(default=True, verbose_name='是否显示名称')),
                ('name_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称字体大小')),
                ('name_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称字体颜色')),
                ('name_loc', models.IntegerField(verbose_name='名称位置')),
                ('loc_left', models.CharField(max_length=20, verbose_name='位置-左')),
                ('loc_top', models.CharField(max_length=20, verbose_name='位置-上')),
                ('size_width', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标宽度')),
                ('size_height', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标高度')),
                ('pause_image', models.ImageField(upload_to='', verbose_name='静止时显示图片')),
                ('play_image', models.ImageField(upload_to='', verbose_name='播放时显示图片')),
                ('sound_file', models.FileField(upload_to='', verbose_name='声音文件')),
                ('sound_length', models.IntegerField(blank=True, null=True, verbose_name='播放时长')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoundMap.SoundMap')),
            ],
        ),
    ]
