# Generated by Django 3.0.3 on 2020-05-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoundMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name_color',
            field=models.CharField(blank=True, default='#000', max_length=20, null=True, verbose_name='名称字体颜色'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name_loc',
            field=models.IntegerField(choices=[(1, '上'), (2, '下'), (3, '左'), (4, '右')], verbose_name='名称位置'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='pause_image',
            field=models.ImageField(height_field='size_height', upload_to='', verbose_name='静止时显示图片', width_field='size_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='icon_image',
            field=models.ImageField(height_field='size_height', upload_to='', verbose_name='图片', width_field='size_width'),
        ),
        migrations.AlterField(
            model_name='soundmap',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='背景图片'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='素材名称')),
                ('is_show_name', models.BooleanField(default=True, verbose_name='是否显示名称')),
                ('name_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称字体大小')),
                ('name_color', models.CharField(blank=True, default='#000', max_length=20, null=True, verbose_name='名称字体颜色')),
                ('name_loc', models.IntegerField(choices=[(1, '上'), (2, '下'), (3, '左'), (4, '右')], verbose_name='名称位置')),
                ('loc_left', models.CharField(max_length=20, verbose_name='位置-左')),
                ('loc_top', models.CharField(max_length=20, verbose_name='位置-上')),
                ('size_width', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标宽度')),
                ('size_height', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标高度')),
                ('pause_image', models.ImageField(height_field='size_height', upload_to='', verbose_name='静止时显示图片', width_field='size_width')),
                ('play_image', models.ImageField(upload_to='', verbose_name='播放时显示图片')),
                ('video_file', models.FileField(upload_to='', verbose_name='视频文件')),
                ('video_length', models.IntegerField(blank=True, null=True, verbose_name='播放时长')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoundMap.SoundMap')),
            ],
        ),
    ]
