# Generated by Django 3.0.3 on 2020-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundMap', '0003_remove_video_play_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content_image',
        ),
        migrations.AddField(
            model_name='image',
            name='content',
            field=models.URLField(blank=True, null=True, verbose_name='内容URL'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='is_show_name',
            field=models.BooleanField(default=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name_color',
            field=models.CharField(blank=True, default='#000', max_length=20, null=True, verbose_name='名称颜色'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名称大小'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='pause_image',
            field=models.ImageField(height_field='size_height', upload_to='', verbose_name='静止显示图片', width_field='size_width'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='play_image',
            field=models.ImageField(upload_to='', verbose_name='播放显示图片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_show_name',
            field=models.BooleanField(default=False, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名称颜色'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名称大小'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size_height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图标高'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size_width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图标宽'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_show_name',
            field=models.BooleanField(default=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name_color',
            field=models.CharField(blank=True, default='#000', max_length=20, null=True, verbose_name='名称颜色'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名称大小'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pause_image',
            field=models.ImageField(height_field='size_height', upload_to='', verbose_name='静止显示图片', width_field='size_width'),
        ),
        migrations.AlterField(
            model_name='video',
            name='size_height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图标高'),
        ),
        migrations.AlterField(
            model_name='video',
            name='size_width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图标宽'),
        ),
    ]
